DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    last_name  VARCHAR(128)                                         NOT NULL,
    first_name VARCHAR(128)                                         NOT NULL,
    patronymic VARCHAR(128),
    birthday   DATE                                                 NOT NULL
);
CREATE UNIQUE INDEX users_unique_all_fields_idx ON users (last_name, first_name, patronymic, birthday);

CREATE TABLE contacts
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER                                              NOT NULL,
    type    VARCHAR(128)                                         NOT NULL,
    value   VARCHAR(128)                                         NOT NULL,
    CONSTRAINT user_type_value_idx UNIQUE (user_id, type, value),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE photos
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id   INTEGER                                              NOT NULL,
    photo_url VARCHAR(1024)                                         NOT NULL,
    CONSTRAINT user_photo_idx UNIQUE (user_id, photo_url),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
)