DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    last_name  VARCHAR(128)                                         NOT NULL,
    first_name VARCHAR(128)                                         NOT NULL,
    patronymic VARCHAR(128)                                         NOT NULL,
    birthday   DATE                                                 NOT NULL,
    email      VARCHAR(128)                                         NOT NULL,
    phone      VARCHAR(15)                                          NOT NULL
);